// Generated by CoffeeScript 1.6.3
(function() {
  var player, recorder;

  recorder = angular.module('Recorder', ['ui-rangeSlider']);

  player = function() {
    return window.controller.plugins.playback.player;
  };

  recorder.controller('Controls', [
    '$scope', '$location', function($scope, $location) {
      $scope.mode = 'record';
      $scope.min = 0;
      $scope.max = 1;
      $scope.$watch('min', function(newVal, oldVal) {
        return player().setPosition(parseFloat(newVal, 10));
      });
      $scope.$watch('max', function(newVal, oldVal) {
        return player().setPosition(parseFloat(newVal, 10));
      });
      $scope.record = function() {
        var hand, _i, _len, _ref;
        $scope.mode = 'record';
        _ref = player().controller.lastConnectionFrame.hands;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          hand = _ref[_i];
          player().controller.emit('handLost', hand);
        }
        return player().record();
      };
      $scope.crop = function() {
        $scope.mode = 'crop';
        return player().pause();
      };
      $scope.playback = function() {
        $scope.mode = 'playback';
        return player().play();
      };
      return $scope.save = function() {
        return saveAs(new Blob([player()["export"]()], {
          type: "text/JSON;charset=utf-8"
        }), 'recording.json');
      };
    }
  ]);

}).call(this);
